# triggers/__init__.py
from .trigger_base import TriggerBase
from .mouse_corner_trigger import MouseCornerTrigger
from .right_button_down_up_down_trigger import RightButtonDownUpDownTrigger
from .right_button_down_right_trigger import RightButtonDownRightTrigger
from .right_button_down_down_left_trigger import RightButtonDownDownLeftTrigger
from .right_button_down_left_up_left_trigger import RightButtonDownLeftUpLeftTrigger
from .right_button_down_left_up_right_trigger import RightButtonDownLeftUpRightTrigger